name: CMake Build (Linux & Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux-x64-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libsdl2-dev libglew-dev libopenal-dev libbullet-dev libfreetype6-dev binutils
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-linux-release
          path: build/TectonicEngine

  build-linux-x64-relwithdebinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libsdl2-dev libglew-dev libopenal-dev libbullet-dev libfreetype6-dev binutils
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - run: cmake --build build --config RelWithDebInfo
      - run: |
          cp build/TectonicEngine build/TectonicEngine.debug
          objcopy --only-keep-debug build/TectonicEngine.debug build/TectonicEngine.debugsymbols
          objcopy --strip-debug --add-gnu-debuglink=build/TectonicEngine.debugsymbols build/TectonicEngine
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-linux-relwithdebinfo
          path: |
            build/TectonicEngine
            build/TectonicEngine.debugsymbols

  build-windows-x64-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows-x64-release
          path: build/Release/TectonicEngine.exe

  build-windows-x64-relwithdebinfo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - run: cmake --build build --config RelWithDebInfo
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows-x64-relwithdebinfo
          path: |
            build/RelWithDebInfo/TectonicEngine.exe
            build/RelWithDebInfo/TectonicEngine.pdb

  build-windows-x86-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A Win32
      - run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows-x86-release
          path: build/Release/TectonicEngine.exe

  build-windows-x86-relwithdebinfo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - run: cmake --build build --config RelWithDebInfo
      - uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows-x86-relwithdebinfo
          path: |
            build/RelWithDebInfo/TectonicEngine.exe
            build/RelWithDebInfo/TectonicEngine.pdb
