name: CMake Build (Linux & Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libsdl2-dev libglew-dev libopenal-dev libbullet-dev libfreetype6-dev binutils

      - name: Configure CMake (Linux)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build (Linux)
        run: cmake --build build --config RelWithDebInfo

      - name: Split debug info (Linux)
        run: |
          cp build/TectonicEngine build/TectonicEngine.debug
          objcopy --only-keep-debug build/TectonicEngine.debug build/TectonicEngine.debugsymbols
          objcopy --strip-debug --add-gnu-debuglink=build/TectonicEngine.debugsymbols build/TectonicEngine
          file build/TectonicEngine

      - name: Upload binary and debug symbols (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-linux
          path: |
            build/TectonicEngine
            build/TectonicEngine.debugsymbols

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake (Windows)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (Windows)
        run: cmake --build build --config Release

      - name: Upload binary and PDB (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows
          path: |
            build/Release/TectonicEngine.exe
            build/Release/TectonicEngine.pdb
