name: CMake Build (Linux & Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Linux x64)
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libsdl2-dev libglew-dev libopenal-dev libbullet-dev libfreetype6-dev binutils

      - name: Configure CMake (Linux x64)
        run: cmake -S . -B buildx64 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build (Linux x64)
        run: cmake --build buildx64 --config RelWithDebInfo

      - name: Split debug info (Linux x64)
        run: |
          cp buildx64/TectonicEngine buildx64/TectonicEngine.debug
          objcopy --only-keep-debug buildx64/TectonicEngine.debug buildx64/TectonicEngine.debugsymbols
          objcopy --strip-debug --add-gnu-debuglink=build/TectonicEngine.debugsymbols buildx64/TectonicEngine
          file buildx64/TectonicEngine

      - name: Upload binary and debug symbols (Linux x64)
        uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-linux
          path: |
            buildx64/TectonicEngine
            buildx64/TectonicEngine.debugsymbols

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake (Windows x64)
        run: cmake -S . -B buildx64 -G "Visual Studio 17 2022" -A x64

      - name: Build (Windows x64)
        run: cmake --build buildx64 --config Release

      - name: Upload binary and PDB (Windows x64)
        uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows
          path: |
            buildx64/Release/TectonicEngine.exe
            buildx64/Release/TectonicEngine.pdb
            
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure CMake (Windows x86)
        run: cmake -S . -B buildx86 -G "Visual Studio 17 2022" -A Win32

      - name: Build (Windows x86)
        run: cmake --build buildx86 --config Release

      - name: Upload binary and PDB (Windows x86)
        uses: actions/upload-artifact@v4
        with:
          name: TectonicEngine-windows-x86
          path: |
            buildx86/Release/TectonicEngine.exe
            buildx86/Release/TectonicEngine.pdb
